### PR TITLE
Added value type support

### PR DESCRIPTION
**Pull request by leastprivilege**
I added support for Claim.ValueType (int, int32, int64, double and bool). This allows using the JWT handler to create OpenID Connect id_tokens that are conforming to the spec (as opposed to string valued claims only).

All tests are still green, so I assume I haven't broken anything ;)

### CODE REVIEW

**Comment by brandwe** [comment]
@leastprivilege: Have you signed the CA? 

@brentsch: Once he does that, can you review this and see if we can push it in to the dev branch?

**Comment by leastprivilege** [comment]
yes. done.

**Comment by brentschmaltz** [comment]
@leastprivilege: thanks, can you point me to the spec section.

**Comment by leastprivilege** [comment]
e.g. http://openid.net/specs/openid-connect-core-1_0.html#IDToken

**Comment by leastprivilege** [comment]
But there are other claims which are not string valued (beyond id token) - e.g. email_verified or phone_number_verified (boolean) or updated_at (number).

**Comment by brentschmaltz** [comment]
Ah, yes, JSON number, etc.  In general, we need a mapping from CLR Claims <-> JSON with extensibility in types created and serialization.

**Comment by brentschmaltz** [comment]
the only reason I haven't pull'd this in yet is that I need round trip tests.  Json numbers need to show up with correct ValueType in ClaimsIdentity claims.

**Comment by brandwe** [comment]
Taking this in to /dev per approval. Thanks @leastprivilege.

**Pull request merged**
